namespace:
  name: taskflow

postgres:
  image: postgres:16
  port: 5432
  database: taskflowdb
  username: taskflow
  password: taskflowpass

backend:
  name: taskflow-backend
  replicas: 1
  image:
    repository: ghcr.io/subbu-balam/taskflow-backend
    tag: latest
    pullPolicy: Always
  port: 8080

frontend:
  name: taskflow-frontend
  replicas: 1
  image:
    repository: ghcr.io/subbu-balam/taskflow-frontend
    tag: latest
    pullPolicy: Always
  port: 80

services:
  backend:
    type: ClusterIP
    port: 8080
  frontend:
    type: NodePort
    port: 80
    nodePort: 30082