apiVersion: apps/v1
kind: Deployment
metadata:
  name: taskflow-frontend
  namespace: taskflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: taskflow-frontend
  template:
    metadata:
      labels:
        app: taskflow-frontend
    spec:
      containers:
        - name: taskflow-frontend
          image: ghcr.io/subbu-balam/taskflow-frontend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80