apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: taskflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:16-alpine
          ports:
            - containerPort: 5432
          envFrom:
            - secretRef:
                name: postgres-secret
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
          readinessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - taskflow_user
                - -d
                - taskflow
            initialDelaySeconds: 10
            periodSeconds: 10
      volumes:
        - name: postgres-storage
          emptyDir: {}