apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.postgres.name }}
  namespace: {{ .Values.namespace.name }}
spec:
  selector:
    app: {{ .Values.postgres.name }}
  ports:
    - port: {{ .Values.postgres.port }}
      targetPort: {{ .Values.postgres.port }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.backend.name }}
  namespace: {{ .Values.namespace.name }}
spec:
  selector:
    app: {{ .Values.backend.name }}
  type: NodePort
  ports:
    - port: {{ .Values.backend.port }}
      targetPort: {{ .Values.backend.port }}
      nodePort: {{ .Values.backend.nodePort }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.frontend.name }}
  namespace: {{ .Values.namespace.name }}
spec:
  selector:
    app: {{ .Values.frontend.name }}
  type: NodePort
  ports:
    - port: {{ .Values.frontend.port }}
      targetPort: {{ .Values.frontend.port }}
      nodePort: {{ .Values.frontend.nodePort }}