apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: {{ .Values.namespace.name }}
spec:
  type: ClusterIP
  selector:
    app: postgres
  ports:
    - port: {{ .Values.postgres.port }}
      targetPort: {{ .Values.postgres.port }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.backend.name }}
  namespace: {{ .Values.namespace.name }}
spec:
  type: {{ .Values.services.backend.type }}
  selector:
    app: {{ .Values.backend.name }}
  ports:
    - port: {{ .Values.services.backend.port }}
      targetPort: {{ .Values.backend.port }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.frontend.name }}
  namespace: {{ .Values.namespace.name }}
spec:
  type: {{ .Values.services.frontend.type }}
  selector:
    app: {{ .Values.frontend.name }}
  ports:
    - port: {{ .Values.services.frontend.port }}
      targetPort: {{ .Values.frontend.port }}
      nodePort: {{ .Values.services.frontend.nodePort }}