server:
  port: 8080

spring:
  application:
    name: taskflow-backend

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:h2:mem:taskflowdb}
    driver-class-name: ${SPRING_DATASOURCE_DRIVER_CLASS_NAME:org.h2.Driver}
    username: ${SPRING_DATASOURCE_USERNAME:sa}
    password: ${SPRING_DATASOURCE_PASSWORD:}

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: ${SPRING_JPA_DATABASE_PLATFORM:org.hibernate.dialect.H2Dialect}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics